name: phytomni-bot
channels:
  - conda-forge
  - defaults
dependencies:
  # Conda packages
  - python=3.12
  - httpx>=0.28.1
  - mcp>=1.12.0
  - openai>=1.93.2
  - pydantic>=2.11.7
  - pydantic-settings>=2.10.1
  - python-dotenv>=1.1.1
  - pyyaml>=6.0.2
  - onnxruntime
  - pip

  # Pip packages
  - pip:
    - esdk-obs-python>=3.25.3
    - markitdown[all]>=0.1.2
