[project]
name = "mcp_server_phytomni"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shang Xie", email = "xieshang0608@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "biopython>=1.85",
    "esdk-obs-python>=3.25.3",
    "httpx>=0.28.1",
    "logomaker>=0.8.6",
    "matplotlib>=3.10.3",
    "mcp>=1.11.0",
    "openai>=1.93.2",
    "pandas>=2.3.1",
    "pycirclize>=1.9.1",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
    "python-dotenv>=1.1.1",
    "pyyaml>=6.0.2",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "pytest-asyncio>=1.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
